GET http://localhost:3500/users
###

GET http://localhost:3500/users/7
###

POST http://localhost:3500/users
Content-Type: application/json

{
    "name": "Melisa Siles",
    "email": "melisa@siles",
    "birthDate": "23/04/2005",
    "nDni": 34567890,
    "credential": {
        "username": "userotree",
        "password": "passtree"
    }
}
###

PUT http://localhost:3500/users/7
Content-Type: application/json

{
    "name": "Melisa Siles",
    "email": "melu@siles",
    "birthDate": "23/04/2005"
}
###
