GET http://localhost:3000/users
token: authenticated
###

GET http://localhost:3000/users/7
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Christian",
    "email": "christian@siles",
    "birthDate": "27/03/1981",
    "nDni": 12345678,
    "credential": {
        "username": "useruno",
        "password": "passuno"
      }
}
###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "id": 9,
    "name": "Victoria Montaño",
    "email": "victoria@montaño",
    "birthDate": "12/01/1961",
    "nDni": 56789012,
    "credential": {
      "id": 9,
      "username": "usercinco",
      "password": "passcinco"
    }
}
###
DELETE http://localhost:3000/users/10
###

// PETICIONES TURNOS

GET http://localhost:3000/turns
###

POST http://localhost:3000/turns
Content-Type: application/json

{
    "date": "19/05/2024",
    "time": "12:00",
    "status": "Confirmado",
    "userId": 1
}
###

GET http://localhost:3000/turns/1
###

PUT http://localhost:3000/turns/1
Content-Type: application/json

{
    "date": "16/05/2024",
    "time": "02:12",
    "status": "Cancelado"
}
###

DELETE http://localhost:3000/turns/3
###